apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerdb-webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playerdb-webapp
  template:
    metadata:
      labels:
        app: playerdb-webapp
    spec:
      containers:
        - name: playerdb-webapp
          image: playerdb-webapp
          imagePullPolicy: Never
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.1
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: apps/v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: playerdb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: playerdb-webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001