server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: nishant
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  data:
    path: src/main/resources/static/data.csv
sleep-api:
  rate: 5