spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: nishant
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    path: src/main/resources/static/data.csv
sleep-api:
  rate: 5