server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://playerdb-mysql:3306/playerdb
#        url: jdbc:mysql://localhost:3306/playerdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  data:
    path: src/main/resources/static/data.csv
sleep-api:
  rate: 5