server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://playerdb-mysql:3306
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  data:
    path: src/main/resources/static/data.csv
sleep-api:
  rate: 5